run:
  skip-files:
    - pkg/get/.*_.*.go
    - cmd/pulumi-resource-aws-native/schema.go

linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - golint
    - gosec
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - structcheck
    - unconvert
    - varcheck
  disable:
    - lll
    - staticcheck
    - megacheck
